server:
  port: 13000
spring:
  datasource:
    url: jdbc:mysql://120.78.140.235:3306/test?useUnicode=true&amp;characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: xiaoxingxing
    type: com.alibaba.druid.pool.DruidDataSource #连接池的类型